name: Exemplo Artifact
run-name: Exemplo workflow para artifact, executado por ${{ github.actor }}
on: 
    workflow_dispatch: 
env: 
  nome-artefato: teste-artefato
jobs:
    upload-artifact:
      runs-on: ubuntu-latest
      steps: 
          - name: Listagem de arquivo
            run: ls
          - name: Gerar alguns arquivos
            run: |
              mkdir artefatos
              echo "Arquivo de teste 01" > ./artefatos/primeiro_arquivo.txt
              echo "Arquivo de teste 02" > ./artefatos/segundo_arquivo.txt
              echo "Arquivo de teste 03" > ./artefatos/terceiro_arquivo.txt
              echo "Arquivo de teste 04" > ./artefatos/quarto_arquivo.txt
          
          - name: Envio dos arquivos
            uses: actions/upload-artifact@v4
            id: upload-artifact
            with:
              name: ${{ env.nome-artefato }}
              path: ./artefatos
              
          - name: Listagem de arquivo
            run: ls
          
          - name: Endereco para obter os artefactos
            run: |
              echo "${{ steps.upload-artifact.outputs.artifact-url }}"
          
    download-artifact:
      runs-on: ubuntu-latest
      needs: [upload-artifact]
      steps:
        - name: Listagem de arquivos
          run: ls
        
        - name: Download Artifactcs
          uses: actions/download-artifact@v4
          with:
            name: ${{ env.nome-artefato }}

        - name: Listagem de arquivos
          run: ls